---
apiVersion: v1
kind: Namespace
metadata:
  name: s3-storage


---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minio-pvc
  namespace: s3-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: thin-csi
  volumeMode: Filesystem


---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: minio
  namespace: s3-storage
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: minio
    spec:
      volumes:
        - name: minio-pvc

          persistentVolumeClaim:
            claimName: minio-pvc
      containers:
        - resources: {}
          readinessProbe:
            tcpSocket:
              port: 9090
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: container
          command:
            - /bin/bash
            - '-c'
          ports:
            - containerPort: 9090
              protocol: TCP
            - containerPort: 9000
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: minio-pvc
              mountPath: /data
          terminationMessagePolicy: File
          image: 'quay.io/minio/minio:latest'
          args:
            - 'minio server /data --console-address :9090'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      nodeSelector:
        node-role.kubernetes.io/worker: ''
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600


---
kind: Service
apiVersion: v1
metadata:
  name: minio-webui
  namespace: s3-storage
  labels:
    app: minio
spec:
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      name: webui
  type: ClusterIP
  selector:
    app: minio
---
kind: Service
apiVersion: v1
metadata:
  name: minio-api
  namespace: s3-storage
  labels:
    app: minio
spec:
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      name: api
  type: ClusterIP
  selector:
    app: minio

---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: webui
  namespace: s3-storage
  labels:
    app: minio
spec:
  host: webui-minio.apps.marcruz.rhbr-lab.com
  to:
    kind: Service
    name: minio-webui
    weight: 100
  port:
    targetPort: webui
  wildcardPolicy: None

---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: s3
  namespace: s3-storage
  labels:
    app: minio
spec:
  host: s3-storage.apps.marcruz.rhbr-lab.com
  to:
    kind: Service
    name: minio-api
    weight: 100
  port:
    targetPort: api
